spring:
    profiles:
        active:
            - dev
---
server:
  port: 8201
spring:
    profiles: dev
    application:
        name: microservicecloudconfig
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka-dev.com:7001/eureka

---
server:
  port: 8202
spring:
    profiles: test
    application:
        name: microservicecloudconfig
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka-test.com:7001/eureka
#请用utf-8格式保存